name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install gettext
      run: sudo apt-get install gettext
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install in develop mode
      run: |
        pip install -e ".[test]"
    - name: Style checks
      run: |
        pre-commit run -a
    - name: Run tests
      run: |
        pytest tests --cov=jupyterlab_translate
